apiVersion: v1
kind: ConfigMap
metadata:
  name: global-config
data:
  # NOTE(ageapps): proxy-protocol doesnÂ´t seem to be supported in GKE
  use-proxy-protocol: "true"
  proxy-send-timeout: "3600"
  proxy-read-timeout: "3600"
  enable-sticky-sessions: "true"
  enable-vts-status: "true"
  affinity: "cookie"
  session-cookie-name: "route"
  session-cookie-hash: "sha1"