apiVersion: v1
kind: ConfigMap
metadata:
  name: global-config
data:
  db.username: node
  db.password: node
  db.database: nodedb
  db.port: "27017"
  db.host: mongo
  app.redis_host: redis
  app.rabbit_host: rabbit
  app.port: "3000"
  app.scalable: "true"
